[project]
name = "streamlit-compound-dashboard"
version = "0.1.0"
description = "Interactive scientific data visualization dashboard"
requires-python = ">=3.8"
dependencies = [
    "streamlit>=1.28.0,<2.0.0",
    "pandas>=1.5.0,<3.0.0",
    "plotly>=5.15.0,<6.0.0",
    "numpy>=1.21.0,<2.0.0",
]
